server:
  port: 8888

logging:
  file.path: logs
  file.name: mylog.log

spring:
  application:
    name: testInterface
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root@2019

mybatis:
  type-aliases-package: com.practice.model
  mapper-locations:
    - mapper/*